language: python
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.4"

virtualenv:
  system_site_packages: true

matrix:
  exclude:
    - env: QT_API=pyqt5
      python: "2.7"

env:
 - QT_API=pyqt4
 - QT_API=pyqt5

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
 - sudo apt-get update

 # Qt
 - python scripts/install-qt.py

 # pytest
 - pip install --quiet pytest pytest-qt pytest-cov pytest-flake8

 # coveralls
 - pip install --quiet coveralls --use-wheel

script:
 - pip install -e . --upgrade 
 - catchsegv py.test --cov qcrash --flake8

after_success:
 - coveralls
